apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
        - name: client
          image: ashimashraf/client
          env:
            - name: FIREBASE_API_KEY
              valueFrom:
                secretKeyRef:
                  name: firebase-api-key
                  key: FIREBASE_API_KEY
            - name: FIREBASE_AUTH_DOMAIN
              valueFrom:
                secretKeyRef:
                  name: firebase-auth-domain
                  key: FIREBASE_AUTH_DOMAIN
            - name: FIREBASE_PROJECT_ID
              valueFrom:
                secretKeyRef:
                  name: firebase-project-id
                  key: FIREBASE_PROJECT_ID
            - name: FIREBASE_STORAGE_BUCKET
              valueFrom:
                secretKeyRef:
                  name: firebase-storage-bucket
                  key: FIREBASE_STORAGE_BUCKET
            - name: FIREBASE_MESSAGING_SENDER_ID
              valueFrom:
                secretKeyRef:
                  name: firebase-messaging-sender-id
                  key: FIREBASE_MESSAGING_SENDER_ID
            - name: FIREBASE_APP_ID
              valueFrom:
                secretKeyRef:
                  name: firebase-app-id
                  key: FIREBASE_APP_ID
            - name: FIREBASE_MEASUREMENT_ID
              valueFrom:
                secretKeyRef:
                  name: firebase-measurement-id
                  key: FIREBASE_MEASUREMENT_ID
---
apiVersion: v1
kind: Service
metadata:
  name: client-srv
spec:
  selector:
    app: client
  ports:
    - name: client
      protocol: TCP
      port: 3000
      targetPort: 3000
